server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankx
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bankx;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    com.bankx.transactions: DEBUG